### ISSUE TITLE
buildroot can't have python2 and python3 at the same time

### ISSUE THREAD

**Issue by glebm** [OpenDingux/buildroot#27]
The buildroot infrastructure does not support having both at the same time:

https://github.com/OpenDingux/buildroot/blob/23c3026aec77d5c5d3fddce27ebe206f281e51bb/package/python3/Config.in#L7

Some OPKs, such as [Skifree](https://github.com/retrogamehandheld/OpenDingux/raw/master/Games%20%26%20Ports/Skifree.opk), require python2.

Not sure if we want to support them or would rather have python3.

**Comment by jezze** [comment]
My gut feeling is that we will not support python2. It's just too old (it has reached its end of life) and as you say buildroot doesn't even support having both at the same time. I could be wrong of course.

**Comment by michaelshmitty** [comment]
I also think no longer supporting Python 2 is a good idea. I'd be happy to look into porting anything that still relies on Python 2 to Python 3. From a quick glance at the source code of Skifree I see the only reason it's using Python 2 is because of the age of the code, it relying on urllib2 (dropped in Python 3 in favor of the requests module) and Pygame 1.9. But even Pygame's migration to version 2.0 now recommends Python 3. I'm sure I'd be able to port it to Python 3. If there are any other opk's or general OD need for Python 2, feel free to mention them here. Happy to look into it.
Thanks for your great work on OD! You can also find me on the RGH discord.

EDIT:
For example, the pygame Skifree port uses the deprecated urllib2 module only for uploading your score to a site that no longer exists:
https://github.com/jesseklein406/skifree/blob/master/skifree.py#L131

**Comment by pcercuei** [comment]
I agree, Python3 was out a decade ago, it's not worth the effort to support both.
